#runtime: python37

#instance_class: F1
#automatic_scaling:
#  max_instances: 1
#  min_instances: 0 
  
runtime: python
env: flex

#entrypoint: gunicorn -b :$PORT main:app
entrypoint: python main.py

runtime_config:
  python_version: 3.7


manual_scaling:
  instances: 1
resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10